server:
  port: 8081
  filter:
    name: "framework-gateway,gateway,default"

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
# CPU 限流, 最大使用率(1=100%, 0.5=50%)
cpu:
  maxUsage: 0.8